// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzj617iVSZl_Fuc_bHwccmcpAB1WZkU3A',
    appId: '1:746041165202:android:8e5241008b8a48b87e6d4b',
    messagingSenderId: '746041165202',
    projectId: 'dentalnews-657c1',
    databaseURL: 'https://dentalnews-657c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentalnews-657c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTMWwZON9F84mbYFGvnDfYg7njZcWqAuQ',
    appId: '1:746041165202:ios:2d5e43f1b23ef1f97e6d4b',
    messagingSenderId: '746041165202',
    projectId: 'dentalnews-657c1',
    databaseURL: 'https://dentalnews-657c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dentalnews-657c1.appspot.com',
    androidClientId: '746041165202-h2frjanvpurjaoea24vm8m7a8mh49qv9.apps.googleusercontent.com',
    iosBundleId: 'org.palmppd.ssru.dentalnews.app',
  );
}
